package db_tests;

import com.sun.mail.util.LineInputStream;
import org.apache.poi.xwpf.usermodel.LineSpacingRule;
import org.testng.annotations.Test;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class DbTestDemo {

    @Test
    public void testDB(){
        String dbUrl = "jdbc:mysql://stack-overflow.cfse9bqqndon.us-east-1.rds.amazonaws.com/CraterDBS";
        String userName = "craterdbuser";
        String password = "ptschool2023";
        String query = "select * from CraterDBS.invoices order by invoice_number desc;";
        //1. Create a connection
        try {
            /**
             * A Connection object represents a connection with a database.
             * A SQL statement is executed through the Connection object.
             * The Connection object is used to create a Statement object.
             */
            Connection connection = DriverManager.getConnection(dbUrl, userName, password);

            //2. Create a statement
            Statement statement = connection.createStatement();


            //3.  Execute our query
            /**
             * A ResultSet object is a table of data representing a database result set,
             * which is usually generated by executing a statement that queries the database.
             * You need to import java.sql.ResultSet class to use this class.
             * It maintains a cursor that points to the current row in the result set.
             * Initially, the cursor is positioned before the first row.
             * The next() method moves the cursor to the next row, and because it returns false when there are no more rows in the ResultSet object,
             * it can be used in a while loop to iterate through the result set.
             * The getXXX() method retrieves the value of a column in the current row.
             * You must specify the column number to retrieve the value of that column.
             *
             */
            ResultSet resultSet = statement.executeQuery(query);
            ResultSetMetaData rsmd = resultSet.getMetaData();
            int colCount = rsmd.getColumnCount();
            for (int i = 1; i <colCount ; i++) {
                //System.out.println("Column name is " + rsmd.getColumnName(i));
                //System.out.println("Column type is " + rsmd.getColumnType(i));
                //System.out.println("Column display size is " + rsmd.getColumnDisplaySize(i));
            }
            List<List<String>> data = new ArrayList<>();

            /**
             * The next() method moves the cursor to the next row in the ResultSet object.
             * Initially, the cursor is positioned before the first row.
             * The next() method returns false when there are no more rows in the ResultSet object.
             */
            while(resultSet.next()){
                //System.out.println(resultSet.getString("invoice_number"));
                List<String> row = new ArrayList<>();
                for (int i = 1; i <colCount ; i++) {
                    //System.out.print(resultSet.getString(i) + "|| ");
                    row.add(resultSet.getString(i));

                }
                data.add(row);
                //System.out.println();
            }

            System.out.println(data);
            resultSet.close();
            statement.close();
            connection.close();


        } catch (SQLException e) {
            System.out.println("Connection not successful");
            e.printStackTrace();
        }


    }


}
